title: Xiaobo's Peronal Website
description: "This is the personal website of Xiaobo YU."
email: "XYu23@gsb.columbia.edu"

markdown: kramdown

#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge

#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
remote_theme: Prithiviksit/minima
theme: minima


#usemathjax: true

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md